export interface TemplateVariables {
	title: string | null;
	subtitle: string | null;
	author: string;
	authors?: string;
	authorsArray: string[];
	year: number | null;
	publishedYear?: number | null;
	releaseDate: string | null;
	publishedDate?: string | null;
	isbn: string | null;
	isbn13?: string | null;
	isbn10?: string | null;
	publisher: string | null;
	language: string | null;
	pages: number | null;
	pageCount?: number | null;
	genres: string;
	genresArray: string[];
	plot: string | null;
	description?: string | null;
	cover: string | null;
	image?: string | null;
	biblioreadsUrl: string | null;
	hardcoverUrl: string | null;
	bookorbitUrl: string;
	bookorbitID: number;
	id?: number;
	status: string;
	rating: number | null;
	startDate: string | null;
	startedAt?: string | null;
	endDate: string | null;
	finishedAt?: string | null;
	seriesName: string | null;
	seriesIndex: string | null;
	goodreadsRating: number | null;
	hardcoverRating: number | null;
	goodreadsID: string | null;
	hardcoverID: string | null;
	[key: string]: unknown; // Allow for additional variables
}
