/**
 * Language formatting for the {{language}} template variable.
 *
 * Pure module: no Obsidian dependency, no runtime dependencies. The static
 * table in `languages.ts` is generated by `scripts/generate-language-table.mjs`
 * from the iso-639-1 / iso-639-2 npm packages (devDependencies only).
 *
 * Supported formats:
 *   - 'as-is'   - return the raw string unchanged
 *   - 'full'    - English name in Title Case
 *   - 'lower'   - English name in lower case
 *   - 'iso6391' - ISO 639-1 alpha-2 code (e.g. 'en')
 *   - 'iso6392' - ISO 639-2 terminological alpha-3 code (e.g. 'eng')
 *
 * Lookup is normalised by trimming, lowercasing, stripping parenthetical text
 * (e.g. "Greek, Modern (1453-)" → "Greek, Modern"), and trying the full string
 * first, then the primary subtag before '-' or '_'. If no entry matches, or the
 * requested code does not exist for the matched language (e.g. a language with
 * no ISO 639-1 code), the original input is returned unchanged.
 */

import { LANGUAGES } from './languages';

export type LanguageFormat =
	| 'as-is'
	| 'full'
	| 'lower'
	| 'iso6391'
	| 'iso6392';

export const LANGUAGE_FORMATS: { value: LanguageFormat; label: string }[] = [
	{ value: 'as-is', label: 'As is' },
	{ value: 'full', label: 'Full name (title case)' },
	{ value: 'lower', label: 'Full name (lower case)' },
	{ value: 'iso6391', label: 'ISO 639-1' },
	{ value: 'iso6392', label: 'ISO 639-2' },
];

interface LanguageRecord {
	alpha2: string;
	alpha3: string;
	name: string;
	aliases: string[];
}

// Build a lowercase reverse index over every known spelling: the English name,
// every alias (bibliographic + terminological ISO 639-2 codes), and the alpha-2
// code itself. The first match in declaration order wins, which keeps the
// canonical English name the preferred spelling.
const NAME_INDEX = new Map<string, LanguageRecord>();
for (const entry of LANGUAGES) {
	const record: LanguageRecord = {
		alpha2: entry.alpha2,
		alpha3: entry.alpha3,
		name: entry.name,
		aliases: entry.aliases,
	};
	const candidates: string[] = [entry.name, entry.alpha2, ...entry.aliases];
	for (const c of candidates) {
		const key = c.trim().toLowerCase();
		if (key && !NAME_INDEX.has(key)) {
			NAME_INDEX.set(key, record);
		}
	}
}

/**
 * Normalises a raw language string for lookup: trims, lowercases, and strips
 * any parenthetical suffix such as "(1453-)" or "(macrolanguage)".
 */
function normaliseKey(raw: string): string {
	return raw
		.trim()
		.toLowerCase()
		.replace(/\s*\([^)]*\)\s*/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();
}

/**
 * Returns the canonical record for a raw language string, or null if no entry
 * matches. Tries the full normalised string first, then the primary subtag
 * before '-' or '_' (e.g. 'en-US' → 'en', 'zh_Hant' → 'zh').
 */
function lookup(raw: string): LanguageRecord | null {
	if (typeof raw !== 'string') return null;
	const full = normaliseKey(raw);
	if (!full) return null;

	const direct = NAME_INDEX.get(full);
	if (direct) return direct;

	const primary = full.split(/[-_]/)[0]?.trim();
	if (primary && primary !== full) {
		return NAME_INDEX.get(primary) ?? null;
	}

	return null;
}

/**
 * Converts a raw language string (as returned by BookOrbit) into the form
 * requested by `format`. If lookup fails, or the requested code does not exist
 * for the matched language, the original input is returned unchanged.
 */
export function formatLanguage(raw: string | null | undefined, format: LanguageFormat): string {
	if (raw === null || raw === undefined) return '';
	if (format === 'as-is') return String(raw);

	const record = lookup(String(raw));
	if (!record) return String(raw);

	switch (format) {
		case 'full':
			return record.name;
		case 'lower':
			return record.name.toLowerCase();
		case 'iso6391':
			return record.alpha2;
		case 'iso6392':
			return record.alpha3;
		default:
			return String(raw);
	}
}